- name: put systemd init file
  template:
    src: cockroachdb.service.j2
    dest: /lib/systemd/system/cockroach.service
    owner: root
    mode: 644
  register: systemd_config

- name: systemctl daemon-reload
  systemd:
    name: cockroach.service
    daemon_reload: yes
    enabled: yes
  when: systemd_config.changed

- name: Start cockroach
  systemd:
    name: cockroach.service
    state: started
  when: systemd_config.changed

- name: init cockroach cluster
  shell: "cockroach init --cluster-name={{cockroach_cluster_name}} --host={{ ansible_fqdn }} --certs-dir={{ cockroach_certs_dir }}"
  become_user: "{{ cockroach_user}}"
  run_once: True
  when: systemd_config.changed